controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

apijson,apixml,apicsv:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

# apixml:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute

# apicsv:
#     resource:
#         path: ../src/Controller/
#         namespace: App\Controller
#     type: attribute


    