controllers:
    resource: ../src/Controller/
    type: attribute

app_login:
    path: /login
    controller: App\Controller\SecurityController::login

app_logout:
    path: /logout

app_dashboard:
    path: /dashboard
    controller: App\Controller\DashboardController::index

app_home:
    path: /
    controller: App\Controller\HomeController::index